### ISSUE TITLE
Mobai big god

### ISSUE THREAD

**Issue by lby1992** [LiqiNew/EventBusHandler#1]
It's so nb you are, why not name it as NoHandler or QigeHandler, I think that is better than EventBusHandler(low b)

**Comment by LiqiNew** [comment]
you are stupid.shit,the Chinese say what foreign words.

**Comment by LiqiNew** [comment]
you are stupid.shit,the Chinese say what foreign words.

**Comment by LiqiNew** [comment]
you are stupid.shit,the Chinese say what foreign words.

**Comment by LiqiNew** [comment]
you are stupid.shit,the Chinese say what foreign words.

**Comment by LiqiNew** [comment]
you are stupid.shit,the Chinese say what foreign words.

**Comment by LiqiNew** [comment]
you are stupid.shit,the Chinese say what foreign words.

**Comment by LiqiNew** [comment]
you are stupid.shit,the Chinese say what foreign words.

**Comment by LiqiNew** [comment]
you are stupid.shit,the Chinese say what foreign words.

**Comment by LiqiNew** [comment]
you are stupid.shit,the Chinese say what foreign words.

**Comment by LiqiNew** [comment]
you are stupid.shit,the Chinese say what foreign words.

**Comment by LiqiNew** [comment]
you are stupid.shit,the Chinese say what foreign words.
